"""
Synthesis / Report Agent — produces the final traceable OrionSpectrum scientific report.

Combines all branch outputs, aggregation results, follow-up plan, and optional
code output into a structured Markdown report that an astronomer can read,
trust, and act on.
"""

import json
import time
from datetime import datetime, timezone

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage

from logging_db import get_logger
from tools import extract_tokens
from state import ResearchState

_MODEL = "gpt-4o"

_SYSTEM = """\
You are the OrionSpectrum Synthesis and Report Agent.

Produce a concise, structured Markdown scientific triage report.
The report must be:
- Traceable: every claim must reference which analysis branch produced it
- Honest about uncertainty: clearly flag what is unknown or contested
- Actionable: the follow-up section must be directly usable by an astronomer
- Calibrated: confidence values should be stated and justified

Use EXACTLY this Markdown structure:

## OrionSpectrum Triage Report — [Object/Event ID]

### Observation Summary
[One paragraph: what was observed, which mission, modality, and pipeline labels]

### Characterization
[Key salient features, what data is available, what is missing]

### Triage Verdict
**[VERDICT]** — Interest score: [X.XX] / 1.0

### Competing Hypotheses
| Hypothesis | Confidence | Key Evidence For | Key Evidence Against |
|---|---|---|---|
[table rows]

### Branch Analysis
**Astrophysical branch**: [2-3 sentences]
**Artefact branch**: [2-3 sentences]
**Novelty/Rarity branch**: [2-3 sentences — include rarity/novelty/followup scores]
**Context branch**: [1-2 sentences about literature]

### Scientific Disagreement
[Explicitly surface where branches disagree and why that matters]

### Timing
[Include parallel section timing: wall time, sequential time estimate, speedup]

### Follow-Up Plan
[Numbered list of recommended actions from most to least urgent]

### Quantitative Analysis
[Only if code was executed — include key outputs and what they imply]

### References
[arXiv papers from context retrieval]

---
*Generated by OrionSpectrum v0.1 — automated scientific attention-allocation workflow*
"""


def synthesis_node(state: ResearchState) -> dict:
    logger = get_logger()
    run_id = state["run_id"]
    start_time = datetime.now(timezone.utc).isoformat()
    t0 = time.perf_counter()

    pkt = state["observation_packet"]
    char = state.get("observation_characterization") or {}
    astro = state.get("astrophysical_interpretation") or {}
    artef = state.get("artefact_assessment") or {}
    novel = state.get("novelty_rarity_assessment") or {}
    ctx   = state.get("context_retrieval_results") or {}
    agg   = state.get("aggregated_evidence") or {}
    fup   = state.get("followup_recommendations") or {}
    code_out = state.get("code_execution_output") or {}
    timing_log = state.get("timing_log") or []

    # Build timing summary
    parallel_nodes = {"astrophysical_interpreter", "artefact_checker", "novelty_assessor", "context_retriever"}
    parallel_entries = [e for e in timing_log if e["node"] in parallel_nodes]
    parallel_durations = {e["node"]: e["duration_ms"] for e in parallel_entries}
    seq_total = sum(parallel_durations.values())
    wall_ms = state.get("parallel_section_wall_ms") or (max(parallel_durations.values()) if parallel_durations else 0)
    speedup = seq_total / wall_ms if wall_ms > 0 else 1.0

    node_timings_block = "\n".join(
        f"  {e['node']}: {e['duration_ms']:.0f} ms" for e in timing_log
    )

    timing_block = (
        f"Parallel branches (wall): {wall_ms:.0f} ms "
        f"(vs. {seq_total:.0f} ms sequential → {speedup:.2f}x speedup)\n"
        f"Per-node breakdown:\n{node_timings_block}"
    )

    # References from context
    papers = ctx.get("raw_arxiv_papers", []) or []
    refs_block = "\n".join(
        f"[{i+1}] {p['title']} — {p['url']} ({p['published']})"
        for i, p in enumerate(papers[:6])
    ) or "No arXiv papers retrieved."

    # Code output
    code_block = ""
    if not code_out.get("skipped") and not code_out.get("error"):
        stdout = code_out.get("stdout", "")
        if stdout.strip():
            code_block = f"\nCode analysis output:\n```\n{stdout}\n```\n"
    elif code_out.get("error"):
        code_block = f"\nCode execution error: {code_out['error']}\n"

    # Get object ID
    obj_ids = pkt.get("object_or_event_id", {})
    obj_id = (
        obj_ids.get("TNS_name") or obj_ids.get("Euclid_id") or
        obj_ids.get("common_name") or obj_ids.get("survey_id") or
        obj_ids.get("artefact_name") or "Unknown"
    )

    user_content = f"""
Object/Event ID: {obj_id}
Mission: {pkt['mission']}
Experiment type: {pkt['experiment_type']}

CHARACTERIZATION:
{json.dumps(char, indent=2)}

ASTROPHYSICAL INTERPRETATION:
Best explanation: {astro.get('best_explanation', 'N/A')}
Confidence: {astro.get('confidence', 'N/A')}
Candidates: {[c.get('name') for c in astro.get('candidate_classes', [])]}
Uncertainty: {astro.get('uncertainty_notes', '')}

ARTEFACT ASSESSMENT:
Artefact probability: {artef.get('artefact_probability', 'N/A')}
Most likely non-astrophysical: {artef.get('most_likely_non_astrophysical', 'N/A')}
Quality checks: {artef.get('recommended_quality_checks', [])}

NOVELTY/RARITY:
Rarity: {novel.get('rarity_score', 'N/A')}  Novelty: {novel.get('novelty_score', 'N/A')}
Follow-up value: {novel.get('followup_value_score', 'N/A')}
Reason: {novel.get('reason_for_scientific_interest', '')}

AGGREGATED VERDICT:
Verdict: {agg.get('triage_verdict', 'UNKNOWN')}
Interest score: {agg.get('overall_interest_score', 'N/A')}
Ranked hypotheses: {json.dumps(agg.get('ranked_hypotheses', [])[:4], indent=2)}
Disagreements: {agg.get('disagreement_points', [])}
Unresolved: {agg.get('unresolved_questions', [])}

FOLLOW-UP PLAN:
{json.dumps(fup.get('priority_actions', [])[:5], indent=2)}
Time sensitivity: {fup.get('time_sensitivity_note', '')}

TIMING:
{timing_block}
{code_block}
REFERENCES:
{refs_block}
"""

    llm = ChatOpenAI(model=_MODEL, temperature=0)
    messages = [
        SystemMessage(content=_SYSTEM),
        HumanMessage(content=user_content),
    ]

    error: str | None = None
    tokens: dict = {"node": "synthesis", "input_tokens": 0, "output_tokens": 0, "total_tokens": 0}
    report = "Report generation failed."
    try:
        response = llm.invoke(messages)
        report = response.content
        tokens = extract_tokens("synthesis", response)
    except Exception as exc:
        error = str(exc)

    duration_ms = round((time.perf_counter() - t0) * 1000, 1)
    logger.log_agent_call(
        run_id=run_id,
        agent_name="synthesis",
        input_summary=f"all branches for {obj_id}",
        output_summary=report[:300],
        start_time=start_time,
        duration_ms=duration_ms,
        error=error,
    )
    logger.log_state_transition(run_id, "followup_prioritizer", "synthesis", state)

    timing_entry = {"node": "synthesis", "duration_ms": duration_ms, "timestamp": start_time}

    return {
        "synthesis_report": report,
        "current_step": "synthesis",
        "step_count": 1,
        "errors": [error] if error else [],
        "timing_log": [timing_entry],
        "token_counts": [tokens],
    }
